### ISSUE TITLE
Problem with .map files

### ISSUE THREAD

**Issue by Br0uge** [alrydia/Alrydia#3]
We had an issue on GitHub concerning .map files for 
https://azgaar.github.io/Fantasy-Map-Generator/
Can you elaborate mistake?

**Comment by yooksi** [comment]
@Br0uge The problem was in the way Git was formatting text based files before they were pushed to remote repo (*'origin'*). Line endings were automatically formatted to an unknown standard, either **LF** or **CRLF**. As far as I understand it Git does this as a standard for building [cross-platform](https://en.wikipedia.org/wiki/Cross-platform_software) software  (usually Linux - Windows compatibility).

> When you view changes in a file, Git handles line endings in its own way. Since you're collaborating on projects with Git and GitHub, Git might produce unexpected results if, for example, you're working on a Windows machine, and your collaborator has made a change in OS X.

This caused a problem with Azgaar's Fantasy Map Generator web application that expected its exported **.map** files to maintain a fixed EOL formatting style. The moments we pulled each others map files from remote, they stopped working because of the post commit change in EOL format.

Commit 4df4b8ea5970df0b85c55321641e74fb64882ce5 addressed this issue by denoting *.map* files as **truly binary** in *.gitattributes* file and prevent them from being automatically reformatted.

Read more about [dealing with line endings](https://help.github.com/en/articles/dealing-with-line-endings) on Github Help.
